### PR TITLE
Updated the file upload process

### LINKED ISSUE #800: Streamline upload process in Create New Analysis workflow
(From [12 Jan 2023 ChRIS weekly status meeting](https://matrix.to/#/!JIamxaDyfGKOnxIaDN:fedora.im/$BotRHv6tYPSqK_y2yimTlSHYzjLPGaFeVZ-qPz8563U?via=fedora.im&via=matrix.org)):

Screenshot from 2023-01-12 10-20-05

On the far right, clicking on "Upload New Data" brings you to a sub-screen with an upload form. When you upload files/folders through the form, that subscreen gives you a list of files (that you can edit, by removing files from the selection with an X icon). You then can click next to continue with analysis set up.

The proposal here is when you click on "Upload New Data" on the screen above, you'll immediately get a "Browse Files..." upload dialog. Make your selection in the dialog, and exit the upload dialog, *then* you'll be brought to the subscreen with the list of files. From there you can remove files from the selection or add additional ones.

So the suggestion here isn't to completely remove the subscreen, but let the user go right to uploading files immediately, then bring up the subscreen as a confirmation, and let them hit "Next" from the subscreen to continue through the workflow. This should streamline the experience and require less clicks / etc.

### PR DESCRIPTION
**Pull request by ciradu2204**
fixes #800 

Before: 

https://user-images.githubusercontent.com/37863089/213473112-dc0e7a53-d3d0-4263-b487-20171776586a.mov

After: 

https://user-images.githubusercontent.com/37863089/214560617-4bf64fbf-f948-496a-9f7e-ab26806dbe7d.mov

### CODE REVIEW

**Comment by PintoGideon** [comment]
Hello @ciradu2204 , With this feature, we want to add the upload right at the Analysis Type Selection Page in the wizard and not show a different screen for local file upload. It's slightly more work.

**Comment by PintoGideon** [comment]
You can probably show the list of files selected somewhere below the selection itself.

**Comment by ciradu2204** [comment]
> You can probably show the list of files selected somewhere below the selection itself.

okay, thanks.

**Review by PintoGideon — DISMISSED** [review]
Hello @ciradu2204 .

I would remove this block of code for now since this triggers the file upload dialog box twice.

```
 React.useEffect(() => {
    if (acceptedFiles.length === 0) {
      open();
    }
  }, [open, state.data.localFiles.length]);
  ```
  Other than that, the changes look good to me.

**Pull request merged**
