### PR TITLE
fix bugs in master branch after pulling

### LINKED ISSUE #679: Bugs in master branch after pulling
image

### PR DESCRIPTION
**Pull request by codeEmpress1**
### What this PR does

- It fixes syntax errors ( an unclosed curly braces in the `createfeed.scss` file and a type error in `QueryBuilder.tsx file`.)
- It removes unused imports

- fixes #679

### CODE REVIEW

**Comment by Timonwa** [comment]
Hi @codeEmpress1, I mentioned this issue and fixed it here: https://github.com/FNNDSC/ChRIS_ui/pull/676#issuecomment-1277390736. You can check it.

**Comment by codeEmpress1** [comment]
@Timonwa that's cool. I think issues like this should be a standalone PR because it needs to be merged as soon as possible. Having it with other issues might delay merging especially when the other issue needs to be reviewed.

**Comment by Timonwa** [comment]
True. But I was already done with my code and needed to confirm I had no merge conflicts b4 I created a pull request. so his error came after and not before.

**Comment by jennydaman** [comment]
Hey @codeEmpress1 thanks for looking into this. It seems like the codebase already moved forward and the latest commit is building again.

**Pull request closed without merging**
