### PR TITLE
fix the hash URL on the fileBrowser breadcrumb

### PR DESCRIPTION
**Pull request by betty-alagwu**
Fixes:  #784

### CODE REVIEW

**Comment by jennydaman** [comment]
@PintoGideon according to the `git blame` you added the `#` there, do you remember what its purpose was?

**Comment by PintoGideon** [comment]
Hey @jennydaman , Unfortunately I don't remember why I added it.

**Comment by betty-alagwu** [comment]
@jennydaman If there is any changes you want me to implement, i will be happy to do so.

**Comment by jennydaman** [comment]
@PintoGideon we should think about this a bit.

@betty-alagwu I'm trying to think of reasons why we would want to add a hash symbol into the URL. Sometimes an undesirable reload happens if you don't add the hash symbol. Would you describe to me how you've tested this change? If possible, it  would be best to add some automatic tests covering the clicking of this breadcrumb.

Since the URL is not supposed to change at all when using this breadcrumb, what is the purpose of the `to` prop anyway?

**Pull request closed without merging**
