### PR TITLE
Enhancing  "My Library" buttons

### LINKED ISSUE #424: Button of 'My Library' is not scaled in different screen resolution
### Problem

f695c809-4cf9-4419-9996-712d420a884e

### PR DESCRIPTION
**Pull request by singhavs**
**Fixes #424 
Enhancing and fixing responsive error of "My Library" buttons**
### Before
WhatsApp Image 2022-04-22 at 6 50 44 AM

### After
WhatsApp Image 2022-04-22 at 6 50 45 AM

### CODE REVIEW

**Comment by asaayushisingh** [comment]
Hey! @PintoGideon .Kindly review it! Thank You!

**Comment by PintoGideon** [comment]
@asaayushisingh  Please send this pr to the outreachy/spring2022 branch

**Comment by asaayushisingh** [comment]
Sure! @PintoGideon , Kindly check it , Thank You!

**Review by jennydaman — APPROVED** [review]

**Review by jennydaman — COMMENTED** [review]
Using margin here does work, though a better solution (more flexible) might be to set rules on the parent, e.g. flexbox?

**Pull request closed without merging**
