### PR TITLE
Patient id not showing and broken padding

### LINKED ISSUE #371: "Patient ID or MRN" text not showing up in mobile version and  Broken padding on (Pack Service orthanc)  button.
'Patient ID or MRN ' on the PAC page. this text is not showing up. when trying in mobile version.  and the "Pack Service Orthanc button'  is broken where I am trying to decrease the width of the screen.
 

Untitled-2022-03-02-0308

### PR DESCRIPTION
**Pull request by codeEmpress1**
### What does this PR do?

Fixes #371  

- It fix the broken padding in pac lookup mobile screen
- It fix patient's ID/MRN field not showing in the mobile screen of pac look up 
- It fix date picker field overflowing in the filter section of pac lookup screen

### CODE REVIEW

**Comment by codeEmpress1** [comment]
**Before**
1. Mobile screen view
image


2. iPad (medium) screen view
image


3. Large screen view (1024px and above)
Screenshot 2022-10-12 at 00 41 36

**Final result after fixes**
1. Mobile view
Screenshot 2022-10-12 at 00 43 42

2. iPad view
image

3. Desktop view
image

**Comment by codeEmpress1** [comment]
@PintoGideon Thank you, I have added the screenshots.

**Comment by jennydaman** [comment]
@codeEmpress1 I really like how this looks!

**Comment by codeEmpress1** [comment]
@jennydaman Thank you!

**Pull request merged**
