### PR TITLE
issue #647 filter date picker correction

### PR DESCRIPTION
**Pull request by AndroGenius-codes**
date picker ui corrected
[date picker fixed.webm](https://user-images.githubusercontent.com/70571088/195105872-389dfe91-354b-4e97-9798-f845b1ea92c6.webm)

### CODE REVIEW

**Comment by AndroGenius-codes** [comment]
@jennydaman  @mairin  i corrected the date picker ui issue. please take a look and review

**Comment by PintoGideon** [comment]
@AndroGenius-codes  Could you please include before and after screenshots for reference please? Also, it would be helpful if you could some more comments explaining your PR. Thank you so much for your contribution.

**Comment by AndroGenius-codes** [comment]
> @AndroGenius-codes Could you please include before and after screenshots for reference please? Also, it would be helpful if you could some more comments explaining your PR. Thank you so much for your contribution

The original issue i created has a video showing how it was before i edited it. And this pull request has a video showing the appearance after i edited it. 

Here is a link with the before video- https://github.com/FNNDSC/ChRIS_ui/issues/647#issue-1403184793.

A video of how the UI looks after is on  this link- 
https://github.com/FNNDSC/ChRIS_ui/pull/655#issue-1404644242

**Comment by jennydaman** [comment]
Similar PR was merged https://github.com/FNNDSC/ChRIS_ui/pull/657

**Pull request closed without merging**
