### PR TITLE
Updated background graphic for ChRIS UI login screen

### PR DESCRIPTION
**Pull request by zrthxn**
Fixes: #220 

- [x] Optimized the background graphic
- [x] Created scaled versions of the graphic for the various sizes used by pattern fly
- [x] Updated the background of the ChRIS UI login screen with the image

### CODE REVIEW

**Comment by zrthxn** [comment]
@mairin 
The previous commits are to be ignored. They were my previous work which I had rolled back but I ran into a few merge conflicts while pulling the latest from `master`. Please only consider the last two, i.e. `7ffce9b` and `ddbae03`

**Comment by mairin** [comment]
Let's not worry about the conflict, we can ask that PR be rebased with this if this gets merged first.

Can you please clean up the commits so the PR is clean?

**Comment by zrthxn** [comment]
Okay I'll just do that

**Review by mairin — COMMENTED** [review]
Hey @zrthxn - I don't think the package-lock.json file should be included in the commit, can you drop it?

I am not sure what happened with the package.json but the diff isn't readable. Can you fix it?

**Comment by mairin** [comment]
@zrthxn It looks like *all* of the diffs are unreadable. What did you use to edit the files?

**Comment by zrthxn** [comment]
The diff of the image files wont be readable since they're binary files. I can see the diffs of the files in the last two commits though. 
I'm just using VS Code so its not because of the editor. Probably because of the changes I pulled and had conflicts.

**Comment by zrthxn** [comment]
I'm just fixing the tree, I know this is a bit of a silly mistake.

**Comment by zrthxn** [comment]
Oh okay. Yes I'll just fix that.
I'll create a new branch, reset it to the master of this repo (not my fork), and rebase the relevant commits onto that from my local master.

**Comment by zrthxn** [comment]
Fixed the problems. Sorry about the mess.

**Review by mairin — COMMENTED** [review]
Wondering why there is a new sizing introduced here and the 2000 px becoming a new xl?

**Comment by zrthxn** [comment]
The 1200px one wasn't being used anywhere so I assumed that's supposed to be the large one. And when I tried different screen sizes around 900 to 1200px the ChRIS logo ended up in the right area.
If that's wrong I'll change it.

**Comment by mairin** [comment]
> The 1200px one wasn't being used anywhere so I assumed that's supposed to be the large one. And when I tried different screen sizes around 900 to 1200px the ChRIS logo ended up in the right area.
> If that's wrong I'll change it.

The only thing im worried abt is messing with what patternfly does... for example is xl a default in patternfly or defined by patternfly? if not, it could break things in unpredictable ways. If it is a patternfly standard then its fine. Does that make sense?

**Comment by zrthxn** [comment]
Yea I get it. I'll check if that's the case otherwise I'll remove that and
mark this for review.

**Comment by PintoGideon** [comment]
Hey @mairin , I have tested the code for the following devices and it looks good to me. Let me know if this PR is ready to be merged.

**Mobile**:

Mobile


**Kindle**:

Kindle

**Laptop**:

Medium_Screen


**Large Screen**:

Large_Screen

**Review by mairin — CHANGES_REQUESTED** [review]
For Kindle and Mobile sizes.... there's no logo to identify what you are logging into. The ChRIS logo is right now baked into the background. If I provide you the plain ChRIS logo as a separate transparent-background file, would it be possible to pop that logo into the blue space above the login fields?
ChRISlogo-white

**Comment by zrthxn** [comment]
Sure I can do that. If possible you can give me the background separately as well so I can put it in the right place for other screens too. I'll just alter the layout a bit to make it work better.

**Comment by mairin** [comment]
@zrthxn Yay, that's awesome! Here is the background sans logo:
bkgd-chris-nodes_no-logo

**Comment by jennydaman** [comment]
@mairin what's the target min screen size? We should document it somewhere.
https://github.com/FNNDSC/ChRIS_ui/pull/216#discussion_r609676672

**Comment by mairin** [comment]
@jennydaman 360 px is the most common width for mobile phones according to a bunch of stats I just looked up - it's certainly the dimensions of my old samsung galaxy, so we could just go with 360 for the minimum.

The breakpoints for PatternFly are here, I don't see a min there (they have a break at 0?) so I would say if we were to pick one it should be 360, and I am surprised PatternFly doesn't have that anywhere:
https://www.patternfly.org/v4/developer-resources/global-css-variables#global-css-variables

**Comment by zrthxn** [comment]
@mairin 
So I've used the `brandImg` attribute that Patternfly gives you and I've slightly overridden some of the styles to get the following two layouts. I've also modified the logo you provided to make it inline, rather than vertical, in order to fit mobile better.

Desktop
Mobile

I've also added the show-password button for which another issue was created but it was a one-line fix.
If you'd rather have the logo as is, this is what it looks like on a normal screen.

Desktop2

**If these are okay then I can continue fine tuning and create all the scaled versions.**

**Comment by mairin** [comment]
@zrthxn This is looking fabulous, thanks for your attention to detail on this. My only doubt here, is whether we just drop the explanatory text below the logo or replace it. It might be nice to have a short text to just explain that this is the main ChRIS UI... but my gut feel is we just drop it. I just posted a thread in Slack to see what others think - 

https://fnndsc.slack.com/archives/CE6GUG4D6/p1618413787003900

**Comment by zrthxn** [comment]
After changing the background according to the discussion on Slack and adding the appropriate logos and text, this is what the page finally looks like.

Screenshot (49)

I've also gone ahead and added a show password button by using PatternFly's built-in attribute for this purpose.

**Review by mairin — APPROVED** [review]
LGTM

**Pull request merged**
